spring.application.name=nonprofit-donation-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/nonprofit_donation_tracker
spring.datasource.username=sumitrac
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
